// End-to-end smoke test of the full PolyShelfCore pipeline, runnable without
// Xcode (XCTest isn't in the Command Line Tools). Exercises: scan → parse →
// tag → search → virtual rename → export/import → rename-on-disk → duplicate
// detection, and verifies the non-destructive invariant with checksums.
import Foundation
import CryptoKit
import PolyShelfCore

var failures = 0
func check(_ condition: Bool, _ name: String, detail: String = "") {
    if condition {
        print("  ✓ \(name)")
    } else {
        failures += 1
        print("  ✗ \(name) \(detail)")
    }
}

func sha(_ url: URL) -> String {
    guard let data = try? Data(contentsOf: url) else { return "unreadable" }
    return SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
}

// MARK: - Corpus

let root = FileManager.default.temporaryDirectory
    .appendingPathComponent("polyshelf-smoke-\(UUID().uuidString)", isDirectory: true)
try FileManager.default.createDirectory(at: root.appendingPathComponent("Printables"), withIntermediateDirectories: true)
defer { try? FileManager.default.removeItem(at: root) }

// Binary STL: 2 triangles, 240mm longest edge (→ "large").
func binarySTL(edge: Float) -> Data {
    var data = Data(count: 80)
    var count = UInt32(2).littleEndian
    data.append(Data(bytes: &count, count: 4))
    let tris: [[(Float, Float, Float)]] = [
        [(0, 0, 0), (edge, 0, 0), (0, 50, 12)],
        [(0, 0, 0), (edge, 0, 0), (edge, 50, 0)],
    ]
    for tri in tris {
        data.append(Data(count: 12))
        for v in tri {
            for f in [v.0, v.1, v.2] {
                var bits = f.bitPattern.littleEndian
                data.append(Data(bytes: &bits, count: 4))
            }
        }
        data.append(Data(count: 2))
    }
    return data
}

let flexiURL = root.appendingPathComponent("Printables/flexi_dragon_presupported.stl")
try binarySTL(edge: 240).write(to: flexiURL)

let asciiURL = root.appendingPathComponent("benchy_boat.stl")
try Data("""
solid benchy
  facet normal 0 0 1
    outer loop
      vertex 0 0 0
      vertex 60 0 0
      vertex 0 31 48
    endloop
  endfacet
endsolid benchy
""".utf8).write(to: asciiURL)

let corruptURL = root.appendingPathComponent("broken.stl")
var corrupt = Data(count: 80)
var bogusCount = UInt32(9999).littleEndian
corrupt.append(Data(bytes: &bogusCount, count: 4))
corrupt.append(Data(repeating: 7, count: 33))
try corrupt.write(to: corruptURL)

let pngBytes = Data([0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A]) + Data((0..<32).map(UInt8.init))
let gcodeURL = root.appendingPathComponent("sliced_benchy.gcode")
try Data("""
; generated by PrusaSlicer
; thumbnail begin 16x16 \(pngBytes.base64EncodedString().count)
; \(pngBytes.base64EncodedString())
; thumbnail end
G28
""".utf8).write(to: gcodeURL)

let dupeURL = root.appendingPathComponent("Printables/dragon_copy.stl")
try binarySTL(edge: 240).write(to: dupeURL) // content-identical to flexi

try Data("not a model".utf8).write(to: root.appendingPathComponent("readme.txt"))

// Snapshot for the non-destructive gate.
let watched = [flexiURL, asciiURL, corruptURL, gcodeURL, dupeURL]
let checksumsBefore = watched.map { sha($0) }

// MARK: - Pipeline

print("▸ scan + enrich + tag")
let dbURL = FileManager.default.temporaryDirectory
    .appendingPathComponent("polyshelf-smoke-\(UUID().uuidString).sqlite")
defer {
    try? FileManager.default.removeItem(at: dbURL)
}
let database = try DatabaseManager(databaseURL: dbURL)
let folderManager = FolderManager(database: database)

var embeddedThumbnails: [Int64: Data] = [:]
let scanner = LibraryScanner(
    database: database,
    folderManager: folderManager,
    enrichmentStages: [
        GeometryEnricher(database: database, thumbnailSink: { id, data in
            embeddedThumbnails[id] = data
        }),
        AutoTagger(database: database),
    ]
)

guard case .added(let folderId) = try folderManager.addFolder(at: root) else {
    fatalError("addFolder failed")
}

let semaphore = DispatchSemaphore(value: 0)
Task {
    defer { semaphore.signal() }
    let enabled: Set<String> = ["stl", "gcode", "3mf"]
    let summary = try await scanner.scan(folderId: folderId, enabledExtensions: enabled)
    check(summary.added == 5, "scan discovers 5 model files (txt ignored)", detail: "got \(summary)")

    let items = try await database.writer.read { try ItemRecord.fetchAll($0) }
    let byName = Dictionary(uniqueKeysWithValues: items.map { ($0.originalName, $0) })

    // Parsing
    let flexi = byName["flexi_dragon_presupported.stl"]!
    check(flexi.triangleCount == 2, "binary STL triangle count")
    check(abs((flexi.bboxX ?? 0) - 240) < 0.01, "binary STL bbox 240mm", detail: "\(String(describing: flexi.bboxX))")
    check(byName["benchy_boat.stl"]?.triangleCount == 1, "ASCII STL parsed")
    check(byName["broken.stl"]?.status == .unreadable, "corrupt STL → unreadable, no crash")
    if let gid = byName["sliced_benchy.gcode"]?.id {
        check(embeddedThumbnails[gid] == pngBytes, "gcode embedded thumbnail extracted")
    } else {
        check(false, "gcode item missing")
    }

    // Tagging (PRD acceptance case)
    let store = TagStore(database: database)
    let flexiTags = Set(try await store.tags(forItem: flexi.id!).map(\.name))
    check(flexiTags.contains("flexi"), "tag: flexi", detail: "\(flexiTags)")
    check(flexiTags.contains("presupported"), "tag: presupported")
    check(flexiTags.contains("large"), "tag: large (240mm)")
    check(flexiTags.contains("stl"), "tag: stl")
    check(flexiTags.contains("printables"), "tag: printables (from folder name)")
    let gcodeTags = Set(try await store.tags(forItem: byName["sliced_benchy.gcode"]!.id!).map(\.name))
    check(gcodeTags.contains("presliced") && gcodeTags.contains("benchy"), "gcode tags", detail: "\(gcodeTags)")

    // Suppression: remove auto tag, re-tag, must not resurrect.
    let flexiTagId = try await store.tags(forItem: flexi.id!).first { $0.name == "flexi" }!.tagId
    try await store.removeTag(tagId: flexiTagId, fromItem: flexi.id!)
    await AutoTagger(database: database).enrich(itemIds: [flexi.id!], rootURL: root)
    let after = Set(try await store.tags(forItem: flexi.id!).map(\.name))
    check(!after.contains("flexi"), "suppressed auto tag never resurrects")

    // Search
    var query = LibraryQuery()
    query.formats = ["stl", "gcode"]
    query.searchText = "presup"
    let q1 = query
    let hits = try await database.writer.read { try LibraryQuery.fetch($0, query: q1) }
    check(hits.count == 1 && hits[0].originalName == "flexi_dragon_presupported.stl", "FTS prefix search")

    // Virtual rename — DB only.
    let itemStore = ItemStore(database: database)
    try await itemStore.setDisplayName("Articulated Dragon — small", itemId: flexi.id!)
    query.searchText = "articul"
    let q2 = query
    let renamed = try await database.writer.read { try LibraryQuery.fetch($0, query: q2) }
    check(renamed.count == 1, "search matches display name after virtual rename")

    // Export → reimport is a no-op (idempotent).
    let exporter = Exporter(database: database, folderManager: folderManager)
    let export1 = try await exporter.export()
    let importer = Importer(database: database, folderManager: folderManager)
    _ = try await importer.importFolder(export1.folders[0], intoFolderId: folderId, policy: .merge)
    let export2 = try await exporter.export()
    check(export1.folders == export2.folders, "export → merge-import → export is idempotent")
    let json = String(data: try Exporter.encode(export1), encoding: .utf8)!
    check(!json.contains(root.path), "export contains no absolute paths")

    // On-disk rename keeps metadata (inode match).
    try FileManager.default.moveItem(
        at: root.appendingPathComponent("benchy_boat.stl"),
        to: root.appendingPathComponent("renamed_boat.stl")
    )
    _ = try await scanner.scan(folderId: folderId, enabledExtensions: enabled)
    let renamedItem = try await database.writer.read { db in
        try ItemRecord.fetchAll(db).first { $0.originalName == "renamed_boat.stl" }
    }
    check(renamedItem?.id == byName["benchy_boat.stl"]?.id, "on-disk rename keeps the same item")

    // Duplicates
    let groups = try await DuplicateFinder(database: database, folderManager: folderManager).findDuplicates()
    check(groups.count == 1 && groups[0].items.count == 2, "duplicate group found by SHA-256", detail: "\(groups.count) groups")
}
semaphore.wait()

// MARK: - Non-destructive gate

print("▸ non-destructive invariant")
let watchedAfter = [flexiURL, corruptURL, gcodeURL, dupeURL, root.appendingPathComponent("renamed_boat.stl")]
let stillIdentical = zip(checksumsBefore, watched).allSatisfy { before, url in
    // benchy_boat.stl was renamed BY THE TEST (not the app) — compare content at new path.
    let current = FileManager.default.fileExists(atPath: url.path)
        ? sha(url)
        : sha(root.appendingPathComponent("renamed_boat.stl"))
    return before == current
}
check(stillIdentical, "all file contents byte-identical after full pipeline")
_ = watchedAfter

print(failures == 0 ? "\nALL CHECKS PASSED" : "\n\(failures) CHECKS FAILED")
exit(failures == 0 ? 0 : 1)
